[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MDS"
version = "0.1.0"
description = "MASLAB 2026 Team 2"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ultralytics",
    "ncnn",
    "numpy",
    "opencv-python",
    "adafruit-circuitpython-bno08x",
    "pyserial",
	"spatialmath-python",
	"maslab-lib @ git+https://github.com/MASLAB/maslab-lib.git@main",
	"shapely"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "autopep8",
    "pyright"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["yolo*", "connection*", "coordinates*", "calibration*"]
exclude = ["runs*", "images*", "profiles*", "venv*", "*.egg-info", "raven"]

[tool.setuptools]
py-modules = []
